languageCode = "fi"
languageName = "Finnish"
weight = 1
# title = "Miss Mira Kira"

[params]
  displayName = "FI"
  isoCode = "fi"
  rtl = false
  dateFormat = "02 01 2006"
  logo = "missmirakira_logo_pink.png"
  secondarylogo = "missmirakira_logo_purple.png"
  description = "Suomalainen AB/DL-, klismafilia-, ja lääkärifetisseihin erikoistunut domina ja sisällöntuottaja."
  copyright = "2023 © Miss Mira Kira"

[author]
  #name = "Miss Mira Kira"
  image = "missmirakira_logo_pink.png"
  headline = "Tamperelainen domina ja sisällöntuottaja, joka on ottanut elämäntehtäväkseen toteuttaa suomalaisten AB/DL-fantasiat."
  # bio = "Some kind of an ABDL/klismaphile/medfet content creating creature from Finland."
  links = [
    { email = "mailto:mail@missmirakira.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/missmirakira" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/missmirakira" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
